mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    # /polls
    path("polls/", views.IndexView.as_view(), name="index"),

    # /polls/1
    path("polls/<int:pk>/", views.DetailView.as_view(), name="detail"),

    # /polls/1/vote
    path("polls/<int:question_id>/vote/", views.vote, name="vote"),

    # /polls/1/results
    path("polls/<int:pk>/results/", views.ResultsView.as_view(), name="results"),


    path("", views.index, name="index"),

    path("purchase/", views.purchase, name="purchase"),

    path("confirmation/", views.order_confirmation, name="order_confirmation"),
]

polls/models.py
from datetime import datetime, timedelta

from django.db import models
from django.utils import timezone


class Product(models.Model):
    # id = models.AutoField(primary_key=True)
    product = models.CharField(max_length=100, blank=False)
    price = models.DecimalField(decimal_places=2, max_digits=100)
    description = models.TextField(blank=True, null=True)
    image_src = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.product


class Customer(models.Model):
    # id = models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=100, blank=False)
    lastName = models.CharField(max_length=100, blank=False)
    street = models.CharField(max_length=100, blank=False)
    plz = models.CharField(max_length=100, blank=False)
    email = models.EmailField(blank=False)

    def __str__(self):
        return " ".join([f"{self.firstName} {self.lastName}", self.email])


class Order(models.Model):
    # id = models.AutoField(primary_key=True)
    orderDate = models.DateTimeField(default=datetime.now)
    articleOrdered = models.ForeignKey(Product, on_delete=models.CASCADE)
    customerID = models.ForeignKey(Customer, on_delete=models.CASCADE)
    amount = models.IntegerField()

    def __str__(self):
        return f'{self.orderDate.strftime("%Y-%m-%d – %H:%m%p")} – {self.customerID}'


class SaleSummary(Order):
    class Meta:
        proxy = True
        verbose_name = 'Sale Summary'
        verbose_name_plural = 'Sales Summary'


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from re import search
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice, Product, Customer, Order


def index(request):
    return render(request, "shop/index.html", {
        "products": Product.objects.all()
    })


def purchase(request):
    if request.method == "GET":
        return index(request)

    new_customer = Customer.objects.create(
        firstName=request.POST["first_name"],
        lastName=request.POST["last_name"],
        street=request.POST["street"],
        plz=request.POST["city"],
        email=request.POST["email"]
    )

    articles_ordered = []
    amounts = []

    for item_key, item_value in request.POST.items():
        if item_key.startswith("product"):
            product_id = search("\d+", item_key).group()
            product_order_count = int(item_value)

            if product_order_count == 0:
                continue

            article = Product.objects.get(id=product_id)
            articles_ordered.append(article)

            amounts.append(product_order_count)

            Order.objects.create(
                customerID=new_customer,
                articleOrdered=article,
                amount=product_order_count
            )

    total_price = sum([amount * product.price for (amount, product)
                       in zip(amounts, articles_ordered)])

    return render(request, "shop/confirmation.html", {
        "customer": new_customer,
        "articles_ordered": zip(amounts, articles_ordered),
        "total_price": total_price
    })

    # return HttpResponseRedirect(reverse("polls:order_confirmation"))


def order_confirmation(request):
    return render(request, "shop/confirmation.html", {})


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])

    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            'question': question,
            'error_message': "You didn’t select a choice."
        })

    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %} {% for choice in question.choice_set.all %}
    <input
      type="radio"
      name="choice"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
    ><br />
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li>
    <a href="{% url 'polls:detail' question.id %}">
      {{ question.question_text }}
    </a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
  </li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/shop/confirmation.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}" />

<section class="section">
  <h2 class="section-headline">
    <small>Bestellbestätigung</small>
    Ihre Bestellung ist eingegangen!
  </h2>

  <div class="checkmark-container">
    <div class="checkmark">✔</div>
  </div>

  <h3>Artikel</h3>

  <ul class="ordered-products">
    {% for amount, product in articles_ordered %}
    <li class="ordered-products-item">
      <span>{{ amount }} &times; {{ product.product }}</span>
      <span>{{ product.price }} €</span>
    </li>
    {% endfor %}
  </ul>

  <p class="total_price">Gesamtpreis: <strong>{{ total_price }} €</strong></p>

  <h3>Versandadresse</h3>
  <p>{{ customer.firstName }} {{ customer.lastName }}</p>
  <p>{{ customer.street }}</p>
  <p>{{ customer.plz }}</p>

  <p>{{ customer.email }}</p>

  <hr />

  <p><a href="{% url 'polls:index' %}">Zurück zur Artikelübersicht</a></p>
</section>

polls/templates/shop/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}" />

<h1>Python-Haushaltswaren24.de</h1>

<form action="{% url 'polls:purchase' %}" method="POST" id="form_order">
  {% csrf_token %}

  <section class="section">
    <h2 class="section-headline">
      <small>Artikelübersicht</small>
      Bestellen Sie noch heute!
    </h2>

    <div class="products">
      {% for product in products %}
      <div class="product">
        <h3>{{ product.product }}</h3>
        <img src="{{ product.image_src }}" class="product-image" />
        <p>{{ product.description }}</p>

        <label
          >Anzahl:
          <select name="product_{{ product.id }}">
            <option>0</option>
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
          </select>
        </label>
        <p class="product-price">€ {{ product.price }}</p>
      </div>
      {% endfor %}
    </div>
  </section>

  <section class="section">
    <h2 class="section-headline">
      <small>Bestellformular</small>
      Ihre Adressangaben
    </h2>

    <fieldset>
      <legend>Anschrift</legend>

      <div class="form-field">
        <label>
          Vorname:
          <input type="text" name="first_name" />
        </label>
      </div>

      <div class="form-field">
        <label>
          Nachname:
          <input type="text" name="last_name" />
        </label>
      </div>

      <div class="form-field">
        <label>
          Straße + Hausnummer:
          <input type="text" name="street" placeholder="" />
        </label>
      </div>

      <div class="form-field">
        <label>
          PLZ + Ort:
          <input type="text" name="city" placeholder="" />
        </label>
      </div>

      <div class="form-field">
        <label>
          E-Mail:
          <input type="text" name="email" placeholder="" />
        </label>
      </div>
    </fieldset>

    <input
      type="submit"
      vakue="Jetzt bestellen"
      class="btn-cta"
      id="btn_order"
    />
  </section>
</form>